export const moviesData = [
  {
    id: "m1",
    title: "Cosmic Odyssey",
    description: "In the near future, a crew of astronauts embark on a perilous voyage through a newly discovered wormhole in search of a new home for humanity, only to find themselves lost in a galaxy ruled by ancient mechanical gods.",
    thumbnail: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    category: "Sci-Fi",
    type: "movie",
    releaseYear: 2025,
    duration: "2h 15m",
    matchPercentage: "98% Match",
    ageRating: "PG-13",
    cast: ["Kaleb Vance", "Aria Sterling", "Dr. David Vance"],
    genres: ["Sci-Fi", "Adventure", "Drama"],
    tags: ["Visual Masterpiece", "Mind-bending", "Exciting"],
    isTrending: true,
    isPopular: true,
    isTopRated: true
  },
  {
    id: "m2",
    title: "Neon Horizon: Tokyo 2099",
    description: "A rogue cyber-detective is forced back into the underworld when a mysterious artificial intelligence hacks the neural networks of Tokyo's elite, threatening to override humanity's free will.",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    category: "Action",
    type: "tv",
    releaseYear: 2026,
    duration: "1 Season",
    matchPercentage: "96% Match",
    ageRating: "TV-MA",
    cast: ["Ren Sato", "Luna Croft", "Marcus Vance"],
    genres: ["Cyberpunk", "Action", "Thriller"],
    tags: ["Gritty", "Suspenseful", "Exciting"],
    isTrending: true,
    isPopular: false,
    isTopRated: true,
    episodes: [
      { id: "e1_1", title: "Neural Drift", duration: "48m", description: "Detective Sato investigates a bizarre suicide of an Android Executive, revealing neural residue from a legendary hacker." },
      { id: "e1_2", title: "The Chrome Alley", duration: "52m", description: "Sato ventures into the black market slums of Tokyo to track down a rogue software dealer, but walks straight into a trap." },
      { id: "e1_3", title: "Ghost in the Network", duration: "45m", description: "Luna executes a dangerous brain-dive into the corporate mainframe to retrieve the decryption keys before they incinerate." }
    ]
  },
  {
    id: "m3",
    title: "Shadows in the Woods",
    description: "After their car breaks down on a remote mountain pass, a group of college students seek shelter in an abandoned logging camp, unaware that a prehistoric predator stalk the surrounding canopy.",
    thumbnail: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    category: "Thriller",
    type: "movie",
    releaseYear: 2024,
    duration: "1h 38m",
    matchPercentage: "92% Match",
    ageRating: "R",
    cast: ["Clarissa Gable", "Tom Jenkins", "Sarah Croft"],
    genres: ["Horror", "Survival", "Thriller"],
    tags: ["Scary", "Suspenseful", "Dark"],
    isTrending: false,
    isPopular: true,
    isTopRated: false
  },
  {
    id: "m4",
    title: "The Laugh Factory",
    description: "Follow the chaotic daily lives of a group of eccentric, struggling stand-up comedians in Chicago trying to make it big at a historical comedy club under the leadership of a hot-tempered legend.",
    thumbnail: "/favicon.svg",
    poster: "/favicon.svg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    category: "Comedy",
    type: "tv",
    releaseYear: 2025,
    duration: "2 Seasons",
    matchPercentage: "88% Match",
    ageRating: "TV-14",
    cast: ["Leo Sterling", "Maya Lin", "Bobby Miller"],
    genres: ["Comedy", "Drama"],
    tags: ["Witty", "Feel-Good", "Hilarious"],
    isTrending: true,
    isPopular: true,
    isTopRated: false,
    episodes: [
      { id: "e2_1", title: "Open Mic Panic", duration: "25m", description: "Maya forgets her punchline in front of a critical talent agent, leading to an impromptu set about her cat." },
      { id: "e2_2", title: "Heckler's Revenge", duration: "22m", description: "Bobby faces a persistent heckler who turns out to be a local food critic writing an undercover review." },
      { id: "e2_3", title: "The Headliner", duration: "28m", description: "When the headlining comic gets stuck at the airport, Leo must stall a rowdy crowd for an hour." }
    ]
  },
  {
    id: "m5",
    title: "Project Titan",
    description: "A hard-hitting documentary exploring the controversial, multi-billion dollar private lunar mining operations and the extreme lives of deep space industrial workers.",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    category: "Documentary",
    type: "movie",
    releaseYear: 2024,
    duration: "1h 55m",
    matchPercentage: "95% Match",
    ageRating: "PG",
    cast: ["Dr. Evelyn Stone (Narrator)"],
    genres: ["Documentary", "Science"],
    tags: ["Informative", "Cerebral", "Captivating"],
    isTrending: false,
    isPopular: false,
    isTopRated: true
  },
  {
    id: "m6",
    title: "Wild Chase: Outback Drift",
    description: "An ex-formula racer is recruited by a government taskforce to infiltrate an underground illegal street racing circuit sprawling across the Australian Outback.",
    thumbnail: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1617469167446-80e3ae1ae79e?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    category: "Action",
    type: "movie",
    releaseYear: 2025,
    duration: "2h 05m",
    matchPercentage: "94% Match",
    ageRating: "PG-13",
    cast: ["Jax Turner", "Elena Rossi", "Cole Harper"],
    genres: ["Action", "Sports", "Thriller"],
    tags: ["Adrenaline Rush", "Fast-Paced", "Exciting"],
    isTrending: true,
    isPopular: true,
    isTopRated: false
  },
  {
    id: "m7",
    title: "Deep Blue Abyss",
    description: "An awe-inspiring cinematic journey into the deepest, unexplored chasms of the Pacific Ocean, revealing bioluminescent ecosystems and never-before-seen creatures.",
    thumbnail: "https://images.unsplash.com/photo-1551244072-5d12893278ab?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    category: "Documentary",
    type: "movie",
    releaseYear: 2025,
    duration: "1h 22m",
    matchPercentage: "97% Match",
    ageRating: "G",
    cast: ["David Attenborough Jr."],
    genres: ["Nature", "Documentary"],
    tags: ["Relaxing", "Breathtaking", "Family-Friendly"],
    isTrending: true,
    isPopular: true,
    isTopRated: true
  },
  {
    id: "m8",
    title: "The Silent Sky",
    description: "When solar flares wipe out global electricity, a pilot and a brilliant meteorologist attempt to fly a steam-powered airship across North America to locate a colony of survivors.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    category: "Sci-Fi",
    type: "movie",
    releaseYear: 2024,
    duration: "2h 10m",
    matchPercentage: "91% Match",
    ageRating: "PG-13",
    cast: ["Liam Sterling", "Ophelia Vance"],
    genres: ["Sci-Fi", "Drama", "Suspense"],
    tags: ["Immersive", "Emotional", "Stunning"],
    isTrending: false,
    isPopular: true,
    isTopRated: true
  },
  {
    id: "m9",
    title: "Code Breakers",
    description: "In the cybernetic spy circles of Switzerland, a codebreaker cracked an cryptographic seal protecting a cache of military drone coordinates, turning him into the world's most hunted target.",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    category: "Action",
    type: "tv",
    releaseYear: 2026,
    duration: "1 Season",
    matchPercentage: "99% Match",
    ageRating: "TV-MA",
    cast: ["Gavin Thorne", "Rebecca Vance", "Kenji Tatsu"],
    genres: ["Cyberpunk", "Suspense", "Action"],
    tags: ["Mind-bending", "Gritty", "Intellectual"],
    isTrending: true,
    isPopular: true,
    isTopRated: true,
    episodes: [
      { id: "e3_1", title: "The Zero Protocol", duration: "44m", description: "Gavin breaks the cryptographic lock on a mysterious hard drive, triggering an immediate military hit-squad assault on his apartment." },
      { id: "e3_2", title: "Dark Web Transit", duration: "50m", description: "On the run, Gavin and Rebecca try to hide in the deep darknet hosting farm of a legendary rogue operative." },
      { id: "e3_3", title: "System Overload", duration: "55m", description: "The final showdown in the Geneva server towers where the coordinates are scheduled to broadcast globally." }
    ]
  },
  {
    id: "m10",
    title: "Chef's Table: Secret Recipes",
    description: "Indulge your senses in the kitchens of remote culinary masters who cook exclusively with native, wild ingredients in the forests of Scandinavia and mountains of Peru.",
    thumbnail: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80",
    poster: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    category: "Documentary",
    type: "tv",
    releaseYear: 2025,
    duration: "1 Season",
    matchPercentage: "93% Match",
    ageRating: "TV-G",
    cast: ["Chef Magnus Nilsson", "Chef Pia Leon"],
    genres: ["Food", "Culture", "Documentary"],
    tags: ["Feel-Good", "Breathtaking", "Inspiring"],
    isTrending: false,
    isPopular: true,
    isTopRated: true,
    episodes: [
      { id: "e4_1", title: "The Arctic Moss", duration: "32m", description: "Chef Magnus demonstrates how to harvest winter lichens and smoke game meat using historical fire pit practices in Northern Sweden." },
      { id: "e4_2", title: "Andean Elevation", duration: "35m", description: "Chef Pia crafts beautiful dishes utilizing clay, high-altitude tubers, and medicinal herbs grown 4,000 meters above sea level." }
    ]
  }
];

export const profilesData = [
  { id: "p1", name: "Raju", avatar: "/avatar-raju.svg", color: "#E50914" },
  { id: "p2", name: "Kids", avatar: "/avatar-kids.svg", color: "#0080FF" },
  { id: "p3", name: "Guest", avatar: "/avatar-guest.svg", color: "#2AD24E" }
];
